CHARACTERS = [

    {
        "id": "blubb_vann",
        "name": "Blubb",
        "sprite": "blubb_vann.png",
        "hp": 140,
        "hp_growth": 10,
        "atk_min": 3,
        "atk_max": 6,
        "atk_growth": 1,
        "attack_speed": 0.8,
        "crit": 0.05,
        "dodge": 0.05,
        "lifesteal": 0.1,
        "armor": 5,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"hp": 0.7, "armor": 0.3},
        "passive": "scaling_shield",
        "rarity": "common",
        "description": "A calm koi spirit that slowly becomes impossible to remove."
    },

    {
        "id": "buzzer_elektrisk",
        "name": "Buzzer",
        "sprite": "buzzer_elektrisk.png",
        "hp": 90,
        "hp_growth": 10,
        "atk_min": 5,
        "atk_max": 10,
        "atk_growth": 1,
        "attack_speed": 1.4,
        "crit": 0.15,
        "dodge": 0.1,
        "lifesteal": 0.0,
        "armor": 2,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"attack_speed": 0.6, "crit": 0.4},
        "passive": "double_strike",
        "rarity": "common",
        "description": "Dual-headed lightning striker that sometimes hits twice."
    },

    {
        "id": "hammy2",
        "name": "Hammy",
        "sprite": "hammy2.png",
        "hp": 110,
        "hp_growth": 10,
        "atk_min": 4,
        "atk_max": 7,
        "atk_growth": 1,
        "attack_speed": 1.0,
        "crit": 0.1,
        "dodge": 0.15,
        "lifesteal": 0.05,
        "armor": 3,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"dodge": 0.6, "attack_speed": 0.4},
        "passive": "evasive_focus",
        "rarity": "common",
        "description": "Survives by slipping through everything and striking back hard."
    },

    {
        "id": "piggy",
        "name": "Piggy",
        "sprite": "piggy.png",
        "hp": 150,
        "hp_growth": 12,
        "atk_min": 2,
        "atk_max": 5,
        "atk_growth": 1,
        "attack_speed": 0.7,
        "crit": 0.02,
        "dodge": 0.03,
        "lifesteal": 0.08,
        "armor": 8,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.1,
        "main_stats": {"hp": 0.75, "armor": 0.25},
        "passive": "ramp_armor",
        "rarity": "common",
        "description": "A walking fortress that gets harder to kill the longer it lives."
    },

    {
        "id": "cooki",
        "name": "Cooki",
        "sprite": "cooki.png",
        "hp": 85,
        "hp_growth": 8,
        "atk_min": 6,
        "atk_max": 12,
        "atk_growth": 2,
        "attack_speed": 1.1,
        "crit": 0.25,
        "dodge": 0.08,
        "lifesteal": 0.0,
        "armor": 1,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"crit": 0.7, "atk": 0.3},
        "passive": "low_hp_crit_scaling",
        "rarity": "common",
        "description": "A brittle crit monster that becomes dangerous when cornered."
    },

    {
        "id": "cheesy",
        "name": "Cheesy",
        "sprite": "cheesy.png",
        "hp": 140,
        "hp_growth": 10,
        "atk_min": 3,
        "atk_max": 6,
        "atk_growth": 1,
        "attack_speed": 1.1,
        "crit": 0.05,
        "dodge": 0.1,
        "lifesteal": 0.08,
        "armor": 4,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"hp": 0.6, "lifesteal": 0.4},
        "passive": "regen_on_damage",
        "rarity": "common",
        "description": "Keeps patching itself up no matter how rough it gets."
    },

    {
        "id": "narwall",
        "name": "Narwall",
        "sprite": "narwall.png",
        "hp": 100,
        "hp_growth": 9,
        "atk_min": 5,
        "atk_max": 10,
        "atk_growth": 2,
        "attack_speed": 0.8,
        "crit": 0.2,
        "dodge": 0.03,
        "lifesteal": 0.0,
        "armor": 2,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"crit": 0.8, "atk": 0.2},
        "passive": "nth_hit_crit",
        "rarity": "common",
        "description": "Every few hits, reality checks in late."
    },

    {
        "id": "stikky",
        "name": "Stikky",
        "sprite": "stikky.png",
        "hp": 90,
        "hp_growth": 8,
        "atk_min": 6,
        "atk_max": 12,
        "atk_growth": 2,
        "attack_speed": 0.9,
        "crit": 0.15,
        "dodge": 0.05,
        "lifesteal": 0.0,
        "armor": 1,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"atk": 0.7, "crit": 0.3},
        "passive": "bleed_on_hit",
        "rarity": "common",
        "description": "Leaves enemies bleeding while pretending it didn’t try that hard."
    },

    {
        "id": "milk",
        "name": "Milk",
        "sprite": "milk.png",
        "hp": 110,
        "hp_growth": 10,
        "atk_min": 4,
        "atk_max": 7,
        "atk_growth": 1,
        "attack_speed": 1.0,
        "crit": 0.08,
        "dodge": 0.08,
        "lifesteal": 0.12,
        "armor": 3,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"lifesteal": 0.7, "hp": 0.3},
        "passive": "lifesteal_scaling_low_hp",
        "rarity": "common",
        "description": "Drains life better when things go wrong."
    },

    {
        "id": "blubber",
        "name": "Blubber",
        "sprite": "blubber.png",
        "hp": 180,
        "hp_growth": 14,
        "atk_min": 2,
        "atk_max": 4,
        "atk_growth": 1,
        "attack_speed": 0.9,
        "crit": 0.0,
        "dodge": 0.02,
        "lifesteal": 0.15,
        "armor": 9,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.2,
        "main_stats": {"hp": 0.6, "lifesteal": 0.4},
        "passive": "damage_reduction_fight_scaling",
        "rarity": "common",
        "description": "The longer you fight it, the worse it gets for you."
    },

    {
        "id": "kirky",
        "name": "Kirky",
        "sprite": "kirky.png",
        "hp": 100,
        "hp_growth": 9,
        "atk_min": 4,
        "atk_max": 7,
        "atk_growth": 1,
        "attack_speed": 1.4,
        "crit": 0.05,
        "dodge": 0.12,
        "lifesteal": 0.05,
        "armor": 3,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"attack_speed": 0.7, "dodge": 0.3},
        "passive": "speed_on_dodge",
        "rarity": "common",
        "description": "Dodging fuels frantic attack bursts."
    },

    {
        "id": "kolera",
        "name": "Kolera",
        "sprite": "kolera.png",
        "hp": 95,
        "hp_growth": 8,
        "atk_min": 5,
        "atk_max": 9,
        "atk_growth": 2,
        "attack_speed": 1.0,
        "crit": 0.25,
        "dodge": 0.05,
        "lifesteal": 0.0,
        "armor": 2,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"crit": 1.0},
        "passive": "pure_crit_spike",
        "rarity": "common",
        "description": "No plan. Just crits."
    },

    {
        "id": "krollefant",
        "name": "Krollefant",
        "sprite": "krollefant.png",
        "hp": 170,
        "hp_growth": 13,
        "atk_min": 3,
        "atk_max": 6,
        "atk_growth": 1,
        "attack_speed": 0.8,
        "crit": 0.05,
        "dodge": 0.08,
        "lifesteal": 0.1,
        "armor": 7,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.1,
        "main_stats": {"hp": 0.5, "armor": 0.5},
        "passive": "armor_to_damage",
        "rarity": "common",
        "description": "Defense that eventually hits back harder."
    },

    {
        "id": "onoff",
        "name": "Onoff",
        "sprite": "onoff.png",
        "hp": 90,
        "hp_growth": 9,
        "atk_min": 3,
        "atk_max": 12,
        "atk_growth": 2,
        "attack_speed": 1.0,
        "crit": 0.1,
        "dodge": 0.05,
        "lifesteal": 0.0,
        "armor": 2,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"atk": 1.0},
        "passive": "toggle_mode",
        "rarity": "common",
        "description": "Switches between tanky and explosive like a broken light switch."
    },

    {
        "id": "pink",
        "name": "Pink",
        "sprite": "pink.png",
        "hp": 120,
        "hp_growth": 10,
        "atk_min": 4,
        "atk_max": 6,
        "atk_growth": 1,
        "attack_speed": 1.2,
        "crit": 0.1,
        "dodge": 0.1,
        "lifesteal": 0.05,
        "armor": 4,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"hp": 0.5, "dodge": 0.5},
        "passive": "adaptive_boost",
        "rarity": "common",
        "description": "Changes style depending on how the fight is going."
    },

    {
        "id": "pointface",
        "name": "Pointface",
        "sprite": "pointface.png",
        "hp": 85,
        "hp_growth": 8,
        "atk_min": 6,
        "atk_max": 10,
        "atk_growth": 2,
        "attack_speed": 1.3,
        "crit": 0.15,
        "dodge": 0.02,
        "lifesteal": 0.0,
        "armor": 1,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"atk": 0.8, "crit": 0.2},
        "passive": "bleed_on_crit",
        "rarity": "common",
        "description": "Cuts that keep hurting after impact."
    },

    {
        "id": "susage",
        "name": "Susage",
        "sprite": "susage.png",
        "hp": 130,
        "hp_growth": 11,
        "atk_min": 3,
        "atk_max": 5,
        "atk_growth": 1,
        "attack_speed": 1.5,
        "crit": 0.2,
        "dodge": 0.2,
        "lifesteal": 0.03,
        "armor": 3,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"dodge": 0.7, "attack_speed": 0.3},
        "passive": "dodge_speed_stacking",
        "rarity": "common",
        "description": "Moves so much it’s basically a blur."
    },

    {
        "id": "vilmaa",
        "name": "Vilmaa",
        "sprite": "vilmaa.png",
        "hp": 110,
        "hp_growth": 10,
        "atk_min": 4,
        "atk_max": 8,
        "atk_growth": 1,
        "attack_speed": 1.1,
        "crit": 0.12,
        "dodge": 0.08,
        "lifesteal": 0.08,
        "armor": 4,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "main_stats": {"atk": 0.4, "crit": 0.3, "lifesteal": 0.3},
        "passive": "random_surge",
        "rarity": "common",
        "description": "Unstable experiment that occasionally spikes in power."
    }
]