CHARACTERS = [
    {
        "id": "blubb_vann",
        "name": "Blubb Vann",
        "sprite": "blubb_vann.png",
        "hp": 140,
        "hp_growth": 10,
        "atk_min": 3,
        "atk_max": 6,
        "atk_growth": 1,
        "attack_speed": 0.8,
        "crit": 0.05,
        "dodge": 0.05,
        "lifesteal": 0.1,
        "armor": 5,
        "magic_resist": 0,
        "magic_damage": 0.0,
        "size": 1.0,
        "on_hit": [],
        "main_stat": "hp",
        "rarity": "common",
        "description": "Tanky lil water blob with sustain."
    },

    {
        "id": "buzzer_elektrisk",
        "name": "Buzzer Elektrisk",
        "sprite": "buzzer_elektrisk.png",
        "hp": 90,
        "hp_growth": 10,
        "atk_min": 5,
        "atk_max": 10,
        "atk_growth": 1,
        "attack_speed": 1.4,
        "crit": 0.15,
        "dodge": 0.1,
        "lifesteal": 0.0,
        "armor": 2,
        "magic_resist": 0,
        "magic_damage": 0.1,
        "size": 1.0,
        "on_hit": ["double_strike"],
        "main_stat": "atk",
        "rarity": "common",
        "description": "Fast attacker with crit bursts."
    },

    {
        "id": "hammy2",
        "name": "Hammy",
        "sprite": "hammy2.png",
        "hp": 110,
        "hp_growth": 10,
        "atk_min": 4,
        "atk_max": 7,
        "atk_growth": 1,
        "attack_speed": 1.0,
        "crit": 0.1,
        "dodge": 0.15,
        "lifesteal": 0.05,
        "armor": 3,
        "magic_resist": 2,
        "magic_damage": 0.0,
        "size": 1.0,
        "on_hit": [],
        "main_stat": "dodge",
        "rarity": "common",
        "description": "Balanced but slippery."
    },

    {
        "id": "piggy",
        "name": "Piggy",
        "sprite": "piggy.png",
        "hp": 150,
        "atk_min": 2,
        "atk_max": 5,
        "attack_speed": 0.7,
        "crit": 0.02,
        "dodge": 0.03,
        "lifesteal": 0.08,
        "armor": 8,
        "magic_resist": 3,
        "magic_damage": 0.0,
        "on_hit": [],
        "main_stat": "hp",
        "description": "A chunky tank that refuses to die."
    },

    {
        "id": "cooki",
        "name": "Cooki",
        "sprite": "cooki.png",
        "hp": 85,
        "atk_min": 6,
        "atk_max": 12,
        "attack_speed": 1.1,
        "crit": 0.25,
        "dodge": 0.08,
        "lifesteal": 0.0,
        "armor": 1,
        "magic_resist": 1,
        "magic_damage": 0.0,
        "on_hit": [],
        "main_stat": "crit",
        "description": "High risk, high reward crit machine."
    },
]